- include_tasks: postgresql.yml
- include_tasks: dev.yml
- include_tasks: pg_qualstats.yml
- include_tasks: pg_stat_kcache.yml
- include_tasks: hypopg.yml
- include_tasks: pg_stat_statements.yml
- include_tasks: powa.yml
- include_tasks: powa_web.yml
